language: go

env: GO111MODULE=on

go:
  - 1.15.x

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - make setup

script:
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
