[server]
host = "0.0.0.0"
port = "5000"

[jwt]
secret = "CHANGE ME!!!"
expire_time = '3m'

[storage.postgres]
    [storage.postgres.default]
    url = "postgres://root:root@localhost:5432/gin_project_starter"